name: riemannian-herding
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.6
  - numpy==1.20.2
  - scipy==1.5.2
  - scikit-learn==0.24.1
  - pytorch==1.8.1
  - matplotlib==3.4.1
  - pip
  - tqdm==4.60.0
  - emcee
  - pip:
      - git+https://github.com/pymanopt/pymanopt.git
      - pyro-ppl==0.4.1
      - git+https://github.com/nicola-decao/s-vae-pytorch
      - POT
#      - autograd==1.3
      - git+https://github.com/HIPS/autograd.git
      - gpytorch==0.3.6
      - git+https://github.com/geoopt/geoopt.git
      - gym
      - pool
